package com.example.stratagempicker.Model;

public class PrePopulation {

	private final Stratagem[] stratagems = {
		new Stratagem(0, "Machine Gun", "dldur", Integer.MAX_VALUE, StratagemType.WEAPON, 0, 1),
		new Stratagem(1, "Anti-Material Rifle", "dlrud", Integer.MAX_VALUE, StratagemType.WEAPON, 0, 1),
		new Stratagem(2, "Stalwart", "dlduul", Integer.MAX_VALUE, StratagemType.WEAPON, 0, 1),
		new Stratagem(3, "Expendable Anti-Tank", "ddlur", Integer.MAX_VALUE, StratagemType.WEAPON, 0, 1),
		new Stratagem(4, "Recoilless Rifle", "dlrrl", Integer.MAX_VALUE, StratagemType.WEAPON, 1, 1),
		new Stratagem(5, "Flamethrower", "dludu", Integer.MAX_VALUE, StratagemType.WEAPON, 0, 1),
		new Stratagem(6, "Autocannon", "dlduur", Integer.MAX_VALUE, StratagemType.WEAPON, 1, 1),
		new Stratagem(7, "Railgun", "drdulr", Integer.MAX_VALUE, StratagemType.WEAPON, 0, 1),
		new Stratagem(8, "Spear", "ddudd", Integer.MAX_VALUE, StratagemType.WEAPON, 1, 1),
		new Stratagem(9, "Orbital Gatling Barrage", "rdluu", Integer.MAX_VALUE, StratagemType.ORBITAL, 0, 1),
		new Stratagem(10, "Orbital Airburst Strike", "rrr", Integer.MAX_VALUE, StratagemType.ORBITAL, 0, 1),
		new Stratagem(11, "Orbital 120mm HE Barrage", "rrdlrd", Integer.MAX_VALUE, StratagemType.ORBITAL, 0, 1),
		new Stratagem(12, "Orbital 380mm HE Barrage", "rduuldd", Integer.MAX_VALUE, StratagemType.ORBITAL, 0, 1),
		new Stratagem(13, "Orbital Walking Barrage", "rdrdrd", Integer.MAX_VALUE, StratagemType.ORBITAL, 0, 1),
		new Stratagem(14, "Orbital Laser Strike", "rdurd", 3, StratagemType.ORBITAL, 0, 1),
		new Stratagem(15, "Orbital Railcannon Strike", "ruddr", Integer.MAX_VALUE, StratagemType.ORBITAL, 0, 1),
		new Stratagem(16, "Eagle Strafing Run", "urr", 4, StratagemType.EAGLE, 0, 1),
		new Stratagem(17, "Eagle Airstrike", "urdr", 2, StratagemType.EAGLE, 0, 1),
		new Stratagem(18, "Eagle Cluster Bomb", "urddr", 4, StratagemType.EAGLE, 0, 1),
		new Stratagem(19, "Eagle Napalm Airstrike", "urdu", 2, StratagemType.EAGLE, 0, 1),
		new Stratagem(20, "Jump Pack", "duudu", Integer.MAX_VALUE, StratagemType.BACKPACK, 1, 1),
		new Stratagem(21, "Eagle Smoke Strike", "urud", 2, StratagemType.EAGLE, 0, 1),
		new Stratagem(22, "Eagle 110mm Rocket Pods", "urul", 2, StratagemType.EAGLE, 0, 1),
		new Stratagem(23, "Eagle 500kg Bomb", "urddd", 1, StratagemType.EAGLE, 0, 1),
		new Stratagem(24, "Orbital Precision Strike", "rru", Integer.MAX_VALUE, StratagemType.ORBITAL, 0, 1),
		new Stratagem(25, "Orbital Gas Strike", "rrdr", Integer.MAX_VALUE, StratagemType.ORBITAL, 0, 1),
		new Stratagem(26, "Orbital EMS Strike", "rrld", Integer.MAX_VALUE, StratagemType.ORBITAL, 0, 1),
		new Stratagem(27, "Orbital Smoke Strike", "rrdu", Integer.MAX_VALUE, StratagemType.ORBITAL, 0, 1),
		new Stratagem(28, "HMG Emplacement", "dulrrl", Integer.MAX_VALUE, StratagemType.EMPLACEMENT, 0, 1),
		new Stratagem(29, "Shield Generator Relay", "ddlrlr", Integer.MAX_VALUE, StratagemType.EMPLACEMENT, 0, 1),
		new Stratagem(30, "Tesla Tower", "durulr", Integer.MAX_VALUE, StratagemType.EMPLACEMENT, 0, 1),
		new Stratagem(31, "Anti-Personnel Minefield", "dldur", Integer.MAX_VALUE, StratagemType.EMPLACEMENT, 0, 1),
		new Stratagem(32, "Supply Pack", "dlduud", Integer.MAX_VALUE, StratagemType.BACKPACK, 1, 1),
		new Stratagem(33, "Grenade Launcher", "dluld", Integer.MAX_VALUE, StratagemType.WEAPON, 0, 1),
		new Stratagem(34, "Laser Cannon", "dldul", Integer.MAX_VALUE, StratagemType.WEAPON, 0, 1),
		new Stratagem(35, "Incendiary Mines", "dlld", Integer.MAX_VALUE, StratagemType.EMPLACEMENT, 0, 1),
		new Stratagem(36, "Guard Dog Rover", "dulurr", Integer.MAX_VALUE, StratagemType.BACKPACK, 1, 1),
		new Stratagem(37, "Ballistic Shield Backpack", "dlddul", Integer.MAX_VALUE, StratagemType.BACKPACK, 1, 1),
		new Stratagem(38, "Arc Thrower", "drdull", Integer.MAX_VALUE, StratagemType.WEAPON, 0, 1),
		new Stratagem(39, "Shield Generator Pack", "dulrlr", Integer.MAX_VALUE, StratagemType.BACKPACK, 1, 1),
		new Stratagem(40, "Machine Gun Sentry", "durru", Integer.MAX_VALUE, StratagemType.EMPLACEMENT, 0, 1),
		new Stratagem(41, "Gatling Sentry", "durl", Integer.MAX_VALUE, StratagemType.EMPLACEMENT, 0, 1),
		new Stratagem(42, "Mortar Sentry", "durrd", Integer.MAX_VALUE, StratagemType.EMPLACEMENT, 0, 1),
		new Stratagem(43, "Guard Dog", "dulurd", Integer.MAX_VALUE, StratagemType.BACKPACK, 1, 1),
		new Stratagem(44, "Autocannon Sentry", "durulu", Integer.MAX_VALUE, StratagemType.EMPLACEMENT, 0, 1),
		new Stratagem(45, "Rocket Sentry", "durrl", Integer.MAX_VALUE, StratagemType.EMPLACEMENT, 0, 1),
		new Stratagem(46, "EMS Mortar Sentry", "durdr", Integer.MAX_VALUE, StratagemType.EMPLACEMENT, 0, 1),
		new Stratagem(47, "Patriot Exosuit", "ldruldd", 2, StratagemType.MECH, 0, 1),
		new Stratagem(48, "Airburst Rocket Launcher", "duulr", Integer.MAX_VALUE, StratagemType.WEAPON, 1, 1),
		new Stratagem(49, "Emancipator Exosuit", "ldruldu", 2, StratagemType.MECH, 0, 1),
		new Stratagem(50, "Anti-Tank Mines", "dluu", Integer.MAX_VALUE, StratagemType.EMPLACEMENT, 0, 1),
		new Stratagem(51, "Orbital Napalm Barrage", "rrdlru", Integer.MAX_VALUE, StratagemType.ORBITAL, 0, 1),
		new Stratagem(52, "Sterilizer", "dludl", Integer.MAX_VALUE, StratagemType.WEAPON, 0, 1),
		new Stratagem(53, "Guard Dog Dog Breath", "duluru", Integer.MAX_VALUE, StratagemType.BACKPACK, 1, 1),
		new Stratagem(54, "Directional Shield", "dulruu", Integer.MAX_VALUE, StratagemType.BACKPACK, 1, 1),
		new Stratagem(55, "Flame Sentry", "durduu", Integer.MAX_VALUE, StratagemType.EMPLACEMENT, 0, 1),
		new Stratagem(56, "Anti-Tank Emplacement", "dulrrr", Integer.MAX_VALUE, StratagemType.EMPLACEMENT, 0, 1),
		new Stratagem(57, "Fast Recon Vehicle", "ldrdrdu", Integer.MAX_VALUE, StratagemType.VEHICLE, 0, 1),
		new Stratagem(58, "W.A.S.P Launcher", "ddudr", Integer.MAX_VALUE, StratagemType.WEAPON, 1, 1),
		new Stratagem(59, "Gas Mines", "dllr", Integer.MAX_VALUE, StratagemType.EMPLACEMENT, 0, 0)
    };

    public Stratagem[] getStratagems() {
        return stratagems;
    }
}